package io.github.marcosox.fsxsaas.fsx;

public enum EVENT_ID {
	AIRPORTS_SCAN,
	WAYPOINTS_SCAN,
	VOR_SCAN,
	NDB_SCAN,
	ON_OBJECT_REMOVED,
	PAUSE,
	SIM_STATUS_CHANGED,
	POSITION_CHANGED,
	AIRCRAFT_LOADED,
	FLIGHT_LOADED,
}
